### ISSUE TITLE
Update of axios to >=0.21.1

### ISSUE THREAD

**Issue by PierreSchwang** [mannyyang/vuetable-3#9]
Hi!

Would it be possible to update vuetables dependency axios to >=0.21.1?

As can be read at https://www.npmjs.com/advisories/1594, lower versions contain strong security vulnerabilities

Best regards

**Comment by mannyyang** [comment]
Yes! That is a great suggestion, will update later today.

**Comment by mannyyang** [comment]
v3.3.3 has been updated with axios v0.21.1.
